---

spring:
  application:
    name: hotelservice
  datasource:
    url: jdbc:mysql://localhost:3306/microservices
    username: goura
    password: Goura@123

server:
  port: 8086

jpa:
  hibernate:
    ddl-auto: update
  show-sql: true
  properties:
    hibernate:
      dialect: org.hibernate.dialect.MySQLDialect

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka